org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# 禁用仓库模式限制，允许在 settings.gradle.kts 中配置仓库
org.gradle.dependency.verification.console=verbose
# 设置 Kotlin 编译器参数，隐藏过时选项警告
kotlin.daemon.jvmargs=-Xmx2048m
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
